apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-consuming-a-configmap
  name: nginx-consuming-a-configmap
  namespace: yc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-consuming-a-configmap
  template:
    metadata:
      labels:
        app: nginx-consuming-a-configmap
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
