apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-nginx
  name: hello-nginx
  namespace: yc
spec:
  type: ClusterIP
  ports:
  - name: 8090-80
    port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-nginx
