apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-nginx
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-nginx
  targetCPUUtilizationPercentage: 75
