apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-nginx-nodeport
  name: hello-nginx-nodeport
  namespace: yc
spec:
  type: NodePort
  ports:
  - name: 8090-80
    nodePort: 31001
    port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-nginx
